#!/usr/bin/env node
/**
 * seed-models.mjs — Creates initial model YAML files from known models
 * discussed in Model Mondays episodes.
 */
import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";

const MODELS_DIR = path.resolve("data/models");
fs.mkdirSync(MODELS_DIR, { recursive: true });

const today = new Date().toISOString().slice(0, 10);

const models = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    family: "GPT",
    category: "multimodal",
    description: "OpenAI's flagship multimodal model — text, vision, and audio in one model with fast inference.",
    catalogUrl: "https://ai.azure.com/explore/models/gpt-4o/version/2024-08-06/registry/azure-openai",
    providerUrl: "https://openai.com/gpt-4o",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models",
    openSource: false,
    status: "active",
    episodes: ["s1-e01-2025-03-11", "s2-e01-2025-06-16"],
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    provider: "OpenAI",
    family: "GPT",
    category: "language",
    description: "OpenAI's large language model with strong reasoning and instruction-following capabilities.",
    catalogUrl: "https://ai.azure.com/explore/models/gpt-4/version/turbo-2024-04-09/registry/azure-openai",
    providerUrl: "https://openai.com/gpt-4",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models",
    openSource: false,
    status: "active",
    episodes: ["s1-e01-2025-03-11"],
  },
  {
    id: "o1",
    name: "o1",
    provider: "OpenAI",
    family: "o-series",
    category: "reasoning",
    description: "OpenAI's reasoning model that thinks before answering, excelling at math, science, and complex logic.",
    catalogUrl: "https://ai.azure.com/explore/models/o1/version/2024-12-17/registry/azure-openai",
    providerUrl: "https://openai.com/o1",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#o1-and-o1-mini-models",
    openSource: false,
    status: "active",
    episodes: ["s1-e02-2025-03-18", "s2-e01-2025-06-16"],
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    family: "o-series",
    category: "reasoning",
    description: "Next-generation reasoning model from OpenAI with enhanced chain-of-thought capabilities.",
    catalogUrl: "https://ai.azure.com/explore/models/o3/registry/azure-openai",
    providerUrl: "https://openai.com/o3",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#o-series-models",
    openSource: false,
    status: "new",
    episodes: ["s2-e01-2025-06-16"],
  },
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "Microsoft",
    family: "Phi",
    category: "small-language",
    description: "Microsoft's state-of-the-art small language model (14B params) — strong reasoning in a compact footprint.",
    catalogUrl: "https://ai.azure.com/explore/models/Phi-4/version/3/registry/azureml",
    providerUrl: "https://azure.microsoft.com/en-us/blog/introducing-phi-4-microsoft-s-newest-small-language-model-specializing-in-complex-reasoning/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/phi-4",
    parameters: "14B",
    openSource: true,
    status: "active",
    episodes: ["s2-e03-2025-06-30", "s3-e03-2025-12-16"],
  },
  {
    id: "phi-3",
    name: "Phi-3",
    provider: "Microsoft",
    family: "Phi",
    category: "small-language",
    description: "Microsoft's capable small model available in mini (3.8B) and medium (14B) variants for on-device AI.",
    catalogUrl: "https://ai.azure.com/explore/models/Phi-3-mini-4k-instruct/version/14/registry/azureml",
    providerUrl: "https://azure.microsoft.com/en-us/blog/introducing-phi-3/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/phi-3",
    parameters: "3.8B–14B",
    openSource: true,
    status: "active",
    episodes: ["s1-e06-2025-04-14", "s2-e08-2025-08-04"],
  },
  {
    id: "llama-4",
    name: "Llama 4",
    provider: "Meta",
    family: "Llama",
    category: "multimodal",
    description: "Meta's latest open-weight model family with native multimodal capabilities and mixture-of-experts architecture.",
    catalogUrl: "https://ai.azure.com/explore/models/Llama-4-Scout-17B-16E-Instruct/registry/azureml-meta",
    providerUrl: "https://llama.meta.com/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/meta",
    openSource: true,
    status: "new",
    episodes: ["s3-e09-2026-03-03"],
  },
  {
    id: "llama-3",
    name: "Llama 3",
    provider: "Meta",
    family: "Llama",
    category: "language",
    description: "Meta's open-weight LLM available in 8B and 70B variants, widely adopted for fine-tuning and deployment.",
    catalogUrl: "https://ai.azure.com/explore/models/Meta-Llama-3.1-70B-Instruct/registry/azureml-meta",
    providerUrl: "https://llama.meta.com/llama3/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/meta",
    parameters: "8B–405B",
    openSource: true,
    status: "active",
    episodes: ["s1-e07-2025-04-21", "s2-e13-2025-09-16"],
  },
  {
    id: "command-r-plus",
    name: "Command R+",
    provider: "Cohere",
    family: "Command",
    category: "language",
    description: "Cohere's enterprise-grade model optimized for RAG, tool use, and multi-step reasoning.",
    catalogUrl: "https://ai.azure.com/explore/models/Cohere-command-r-plus-08-2024/registry/azureml-cohere",
    providerUrl: "https://cohere.com/command",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/studio/how-to/deploy-models-cohere-command",
    openSource: false,
    status: "active",
    episodes: ["s3-e14-2026-04-07"],
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "Mistral AI",
    family: "Mistral",
    category: "language",
    description: "Mistral's flagship model for complex reasoning, multilingual tasks, and code generation.",
    catalogUrl: "https://ai.azure.com/explore/models/Mistral-Large-2/registry/azureml-mistral",
    providerUrl: "https://mistral.ai/technology/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/mistral-ai",
    openSource: false,
    status: "active",
    episodes: ["s1-e07-2025-04-21"],
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    provider: "DeepSeek",
    family: "DeepSeek",
    category: "reasoning",
    description: "Open-source reasoning model with strong math and coding capabilities via reinforcement learning.",
    catalogUrl: "https://ai.azure.com/explore/models/DeepSeek-R1/registry/azureml",
    providerUrl: "https://www.deepseek.com/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/deepseek",
    parameters: "671B",
    openSource: true,
    status: "active",
    episodes: ["s2-e01-2025-06-16", "s3-e01-2025-12-02"],
  },
  {
    id: "claude-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    family: "Claude",
    category: "language",
    description: "Anthropic's balanced model offering strong performance across reasoning, analysis, and code at moderate cost.",
    catalogUrl: "https://ai.azure.com/explore/models/claude-3-5-sonnet/registry/azureml-anthropic",
    providerUrl: "https://www.anthropic.com/claude",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/anthropic",
    openSource: false,
    status: "active",
    episodes: ["s3-e08-2026-02-23"],
  },
  {
    id: "whisper",
    name: "Whisper",
    provider: "OpenAI",
    family: "Whisper",
    category: "speech",
    description: "Open-source automatic speech recognition model trained on 680K hours of multilingual audio.",
    catalogUrl: "https://ai.azure.com/explore/models/openai-whisper-large-v3/registry/azureml",
    providerUrl: "https://openai.com/research/whisper",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai-services/speech-service/whisper-overview",
    openSource: true,
    status: "active",
    episodes: ["s2-e11-2025-08-25"],
  },
  {
    id: "dall-e-3",
    name: "DALL·E 3",
    provider: "OpenAI",
    family: "DALL·E",
    category: "image-generation",
    description: "OpenAI's latest image generation model with improved prompt following and text rendering.",
    catalogUrl: "https://ai.azure.com/explore/models/dall-e-3/registry/azure-openai",
    providerUrl: "https://openai.com/dall-e-3",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#dall-e",
    openSource: false,
    status: "active",
    episodes: ["s1-e04-2025-04-01"],
  },
  {
    id: "florence-2",
    name: "Florence-2",
    provider: "Microsoft",
    family: "Florence",
    category: "vision",
    description: "Microsoft's foundation vision model for tasks like captioning, object detection, and visual grounding.",
    catalogUrl: "https://ai.azure.com/explore/models/Florence-2-large/registry/azureml",
    providerUrl: "https://www.microsoft.com/en-us/research/project/projectflorence/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/microsoft",
    openSource: true,
    status: "active",
    episodes: ["s1-e04-2025-04-01", "s2-e10-2025-08-19"],
  },
  {
    id: "mai-1",
    name: "MAI-1",
    provider: "Microsoft",
    family: "MAI",
    category: "language",
    description: "Microsoft's proprietary large language model for enterprise-grade AI applications.",
    catalogUrl: "https://ai.azure.com/explore/models/MAI-DS-R1/registry/azureml",
    providerUrl: "https://azure.microsoft.com/en-us/blog/tag/mai/",
    learnUrl: "https://learn.microsoft.com/en-us/azure/ai/foundry/models/collections/microsoft",
    openSource: false,
    status: "active",
    episodes: ["s3-e06-2026-02-02"],
  },
];

let created = 0;
for (const model of models) {
  model.statusUpdatedAt = today;
  model.provenance = "seed:manual-curation";
  const filePath = path.join(MODELS_DIR, `${model.id}.yaml`);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, yaml.dump(model, { lineWidth: 120, noRefs: true }));
    created++;
  }
}
console.log(`Created ${created} model files in data/models/`);
